name: Deploy Flutter Web

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: flutter-web-build
                  path: build/web/*  # Upload only the files inside the build/web directory

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Download Web Build Artifact
              uses: actions/download-artifact@v4
              with:
                  name: flutter-web-build
                  path: build/web

            - name: Check Secrets (for Debugging)
              run: |
                echo "VPS_HOST: ${{ secrets.VPS_HOST }}"
                echo "VPS_USER: ${{ secrets.VPS_USER }}"
              # This is for debugging purposes; remove this step after confirming secrets are correct

            - name: Synchronize Files To Server
              uses: easingthemes/ssh-deploy@v2.1.5
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key from GitHub Secrets
                SOURCE: "build/web/*"  # Path to the build output files
                REMOTE_HOST: ${{ secrets.VPS_HOST }}  # Server IP/hostname
                REMOTE_USER: ${{ secrets.VPS_USER }}  # SSH user (e.g., ubuntu or root)
                TARGET: "/var/www/ringq_click2call"  # Target directory on the server

            - name: Set Correct Permissions
              uses: appleboy/ssh-action@v0.1.6
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    sudo chown -R www-data:www-data /var/www/ringq_click2call
                    sudo chmod -R 755 /var/www/ringq_click2call

            - name: Ensure .env Has Correct Settings (if applicable)
              uses: appleboy/ssh-action@v0.1.6
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    # Add any necessary steps to update server settings if applicable
                    # For example, setting environment variables or ensuring configuration
                    echo "Flutter web deployment completed"
