name: Deploy Flutter Web

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set Up Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: 'stable'  # Specify Flutter version (e.g., stable)

            - name: Install Dependencies
              run: |
                flutter pub get

            - name: Build Flutter Web
              run: |
                flutter build web --release

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: flutter-web-build
                  path: build/web/*  # Upload only the files inside the build/web directory

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Download Web Build Artifact
              uses: actions/download-artifact@v4
              with:
                  name: flutter-web-build
                  path: build/web 

            - name: Check Secrets (for Debugging)
              run: |
                echo "VPS_HOST: ${{ secrets.VPS_HOST }}"
                echo "VPS_USER: ${{ secrets.VPS_USER }}" 
              # This is for debugging purposes; remove this step after confirming secrets are correct

            - name: Set up SSH Key
              run: |
                mkdir -p ~/.ssh
                echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
                chmod 600 ~/.ssh/deploy_key
                ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Synchronize Files To Server
              run: |
                rsync -avz --delete -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" build/web/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/ringq_click2call
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                VPS_USER: ${{ secrets.VPS_USER }}
                VPS_HOST: ${{ secrets.VPS_HOST }}

            - name: Set Correct Permissions
              uses: appleboy/ssh-action@v0.1.6
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    sudo chown -R www-data:www-data /var/www/ringq_click2call
                    sudo chmod -R 755 /var/www/ringq_click2call

            - name: Ensure .env Has Correct Settings (if applicable)
              uses: appleboy/ssh-action@v0.1.6
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    # Add any necessary steps to update server settings if applicable
                    # For example, setting environment variables or ensuring configuration
                    echo "Flutter web deployment completed"
