name: Deploy Flutter Web test

on:
    push:
        branches:
            - master 

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: flutter-web-build
                  path: build/web/*  # Upload only the files inside the build/web directory

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Download Web Build Artifact
              uses: actions/download-artifact@v4
              with:
                  name: flutter-web-build
                  path: build/web

            - name: Deploy to Server
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: "build/web/*"
                  target: "/var/www/ringq_click2call"
